name: workflow Github4Women

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0
            5.0

      - name: Baixar as dependências
        run: dotnet restore

      - name: Executar testes unitários
        run: dotnet test

      - name: Compilar o WebApp
        run: dotnet build --no-restore
